services:
  bank-db:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  bank-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - bank-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bank-db:5432/bank_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres