spring:
  application:
    name: Bank-card-management
    version: 1.0.0
  datasource:
    url: jdbc:postgresql://localhost:5435/bank_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8080

logging:
  file:
    name: banklogs.log
  ##name: ${pwd}/banklogs.log


my:
  jwt:
    secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

